- name: Run a one-line script
  run: echo Hello, world

# Setting up SSH

- name: Setup SSH agent
  uses: webfactory/ssh-agent@v0.4.0
  with:
    ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

- name: Setup known_hosts
  run: echo '${{ secrets.SSH_HOST }}' >> ~/.ssh/known_hosts

- name: Sync project files
  run: rsync -uvzr --backup --backup-dir='/home/ubuntu/' ${{ secrets.SSH_LOCATION }}
