name: Deploy to AWS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync

      - name: Write SSH key to file
        run: echo "${{ secrets.AWS_SSH_KEY }}" > /home/ubuntu/.ssh/id_rsa && chmod 600 /home/ubuntu/.ssh/id_rsa

      - name: Add SSH host to known_hosts
        run: ssh-keyscan -H ${{ secrets.AWS_SERVER_IP }} >> /home/ubuntu.ssh/known_hosts

      - name: Sync project files to AWS
        run: |
          rsync -avz --backup --backup-dir='/home/ubuntu/backup' ${GITHUB_WORKSPACE}/ ubuntu@${{ secrets.AWS_SERVER_IP }}:/var/www/html

      - name: Restart Nginx on AWS
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.AWS_SERVER_IP }} 'sudo systemctl restart nginx'
